# Generated by Django 3.2.5 on 2021-07-11 11:59

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(blank=True, default=project.models.randomNo)),
                ('category_name', models.CharField(blank=True, max_length=200)),
                ('category_description', models.CharField(blank=True, max_length=200, null=True)),
                ('product_thumbnail', models.FileField(blank=True, null=True, upload_to='productCategoryImages/')),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, default=project.models.randomNo, max_length=100, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('product_description', models.CharField(max_length=200)),
                ('product_images', models.FileField(blank=True, db_column='product_images', null=True, upload_to='productImages/')),
                ('product_price', models.FloatField(null=True)),
                ('gst', models.IntegerField(blank=True, default=0, null=True)),
                ('product_status', models.CharField(max_length=200)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('product_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.product_category')),
            ],
        ),
    ]
