# Generated by Django 3.2.5 on 2021-07-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_images',
            field=models.FileField(blank=True, db_column='product_images', null=True, upload_to='Images/ProductImages'),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='product_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='Images/ProductCategoriesImage'),
        ),
    ]
