# Generated by Django 3.2.5 on 2021-07-11 13:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210711_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_start_date', models.DateTimeField(blank=True, null=True)),
                ('offer_end_date', models.DateTimeField(blank=True, null=True)),
                ('offer_title_name', models.CharField(blank=True, max_length=200, null=True)),
                ('offers_on_product', models.IntegerField(blank=True, null=True)),
                ('offer_post', models.CharField(blank=True, max_length=800, null=True)),
                ('offer_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, default=project.models.randomNo, max_length=100, unique=True)),
                ('order_value', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('payable_amount', models.FloatField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('wallet', 'wallet'), ('cod', 'cod'), ('debit_card', 'debit_card'), ('credit_card', 'credit_card')], max_length=20, null=True)),
                ('order_status', models.CharField(blank=True, choices=[('book', 'book'), ('pending', 'pending'), ('In Stock', 'In Stock'), ('Out Of Range', 'Out Of Range'), ('Cancelled By Customer', 'Cancelled By Customer')], default='book', max_length=100, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('subTotal', models.FloatField(blank=True, default=0.0, null=True)),
                ('deliveryCharges', models.FloatField(blank=True, default=25.0, null=True)),
                ('taxCharges', models.FloatField(blank=True, default=0.0, null=True)),
                ('discountCouponCode', models.CharField(blank=True, max_length=100, null=True)),
                ('grandTotal', models.FloatField(blank=True, default=0.0, null=True)),
                ('offer_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.offer')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
